name: 构建 Windows 应用程序

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write # 添加写入内容的权限
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        
    - name: 安装依赖
      run: npm ci
      
    - name: 构建应用
      run: npm run dist:win
      
    - name: 列出构建产物
      run: dir release /s
      shell: cmd
      
    - name: 上传构建产物到Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/*.exe
          release/*/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true # 即使发生错误也继续执行
        
    # 备份上传方案
    - name: 上传构建产物到Actions Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: release/
        retention-days: 30